language: ruby
cache: bundler
bundler_args: --without tools benchmarks
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - jruby-9.2.7.0
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
