language: ruby
script: 'bundle exec rake test:coverage'
sudo: false
cache: bundler
install: true
env:
  global:
    - JRUBY_OPTS=--dev
script:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby" ]]; then rvm get head && rvm reload && rvm use --install $TRAVIS_RUBY_VERSION; fi'
  - 'bundle install'
  - 'bundle exec rake test:coverage'
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
